function [x,y,z,u,v] = paramWavyTorus(N, cen)
%PARAMWAVYTORUS  A parameterization of the five-fold corrugated wavy torus.
%   [x,y,z] = paramWavyTorus(N) returns a mesh with roughly N points in
%   each parameter direction.  SURF(x,y,z) can be used to make a plot.
%
%   [x,y,z] = paramWavyTorus(N, cen) returns a mesh centered at cen.
%
%   [x,y,z,u,v] = paramWavyTorus(...) also returns the (u,v)
%   parameter values used, e.g., for use as the "surfmesh" initial
%   guess in cpParamSurface (see cpWavyTorus.m).
%
%   Matches the surface generated by make_wavy_torus.m (see meshgen/).

  if (nargin < 1) || isempty(N)
    N = 100;
  end
  if (nargin < 2) || isempty(cen)
    cen = [0 0 0];
  end

  N = max(3, N);

  uu = 0:(2*pi/N):(2*pi);
  vv = 0:(2*pi/N):(2*pi);
  [u,v] = meshgrid(uu, vv);

  R = 2.05 + 0.24*cos(5*u);
  zc = 0.18*sin(5*u);
  r = 0.52 * (1 + 0.13*cos(3*v + 2*u));

  x = (R + r.*cos(v)) .* cos(u);
  y = (R + r.*cos(v)) .* sin(u);
  z = zc + r.*sin(v);

  x = x + cen(1);
  y = y + cen(2);
  z = z + cen(3);
