function [x,y,z,u,v] = paramTwistedEllipticTorus(N, cen)
%PARAMTWISTEDELLIPTICTORUS  A parameterization of the twisted elliptic torus.
%   [x,y,z] = paramTwistedEllipticTorus(N) returns a mesh with roughly
%   N points in each parameter direction.  SURF(x,y,z) can be used to
%   make a plot.
%
%   [x,y,z] = paramTwistedEllipticTorus(N, cen) returns a mesh centered
%   at cen.
%
%   [x,y,z,u,v] = paramTwistedEllipticTorus(...) also returns the
%   (u,v) parameter values used, e.g., for use as the "surfmesh"
%   initial guess in cpParamSurface (see cpTwistedEllipticTorus.m).
%
%   Matches the surface generated by make_twisted_elliptic_torus.m
%   (see meshgen/).

  if (nargin < 1) || isempty(N)
    N = 100;
  end
  if (nargin < 2) || isempty(cen)
    cen = [0 0 0];
  end

  N = max(3, N);

  uu = 0:(2*pi/N):(2*pi);
  vv = 0:(2*pi/N):(2*pi);
  [u,v] = meshgrid(uu, vv);

  R = 2.15;
  a = 0.62;
  b = 0.34;
  twists = 3;

  alpha = twists*u;
  radial = R + a*cos(v).*cos(alpha) - b*sin(v).*sin(alpha);

  x = radial .* cos(u);
  y = radial .* sin(u);
  z = a*cos(v).*sin(alpha) + b*sin(v).*cos(alpha);

  x = x + cen(1);
  y = y + cen(2);
  z = z + cen(3);
